site_name: My project Docs 
theme:
  name: material
  palette:
    primary: blue
    accent: green
  font:
    text: Calibri
    code: Roboto Mono
  language: en
  icon:
    logo: material/library
  features:
    - navigation.expand
    - header.autohide
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/github
      link: https://github.wdf.sap.corp
    - icon: fontawesome/brands/slack
      link: https://sap.enterprise.slack

nav:
  - Home: index.md
  - General:
    - Screen: general/screen.md
    - Video Call: general/video_call.md
  - Devices:
    - Laptop: devices/laptop.md
    - Desktop: devices/desktop.md
    - Accessories: devices/accessories.md
  - About: about.md